#!/usr/bin/env bash

sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3-dev python-dev libpython3.6-dev python3.6 python3-pip python3-tk python3-dev virtualenv

python3 -V

virtualenv -p python3.6 venv
. ./venv/bin/activate

pip install --upgrade pip
pip install -r ./requirements.txt
